# Generated by Django 3.0.9 on 2020-10-21 18:51

from django.db import migrations, models
import faces.models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_auto_20201015_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=faces.models.imgpath),
        ),
    ]
